### PR TITLE
this fix it?

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mjrdnk** [comment]
hmm there are still conflicts

**Review by mjrdnk — APPROVED** [review]

**Comment by mjrdnk** [comment]
Thanks for your contrib @etisdew !

**Comment by ghost** [comment]
Thank you man, sorry about that I had to learn how to resolve a conflict and you beat me to it by seconds. lol It actually said "this is old, do it again." in a couple more words.

**Comment by mjrdnk** [comment]
What said that? :) I am happy that you can learn here :)

**Pull request merged**
